import {
  BarChart3,
  BriefcaseBusiness,
  ClipboardCheck,
  CreditCard,
  Database,
  FileBarChart,
  FileText,
  FolderKanban,
  Languages,
  LogOut,
  Settings,
  UploadCloud,
  Users,
  UserCog,
  UserRoundPlus,
} from 'lucide-react'

export const roles = ['Admin', 'Manager', 'Vendor', 'QC Team']

export const sidebarItems = [
  { id: 'dashboard', label: 'Dashboard', icon: BarChart3 },
  { id: 'leads', label: 'Leads Management', icon: UserRoundPlus },
  { id: 'legal-pages', label: 'Legal Pages', icon: FileText },
  { id: 'jobs', label: 'Job Management', icon: BriefcaseBusiness },
  { id: 'applications', label: 'Applications', icon: ClipboardCheck },
  { id: 'users', label: 'User Management', icon: Users },
  { id: 'vendors', label: 'Vendor Management', icon: BriefcaseBusiness },
  { id: 'dc-team', label: 'DC Team Management', icon: UserCog },
  { id: 'projects', label: 'Project Management', icon: FolderKanban },
  { id: 'languages', label: 'Language Management', icon: Languages },
  { id: 'collection', label: 'Data Collection', icon: Database },
  { id: 'uploads', label: 'Upload Management', icon: UploadCloud },
  { id: 'quality', label: 'Quality Check', icon: ClipboardCheck },
  { id: 'payments', label: 'Payment Management', icon: CreditCard },
  { id: 'reports', label: 'Reports', icon: FileBarChart },
  { id: 'settings', label: 'Settings', icon: Settings },
  { id: 'logout', label: 'Logout', icon: LogOut },
]

export const pageCopy = {
  leads: ['Search submitted leads', 'Filter by status', 'Update lead status', 'Delete lead', 'Export leads', 'Lead detail modal'],
  'legal-pages': ['Create legal pages', 'SEO fields', 'Publish controls', 'Preview content', 'Draft workflow', 'Delete confirmation'],
  jobs: ['Post jobs', 'Edit openings', 'Publish or close', 'Duplicate jobs', 'Preview public role', 'Search and filter'],
  applications: ['Candidate table', 'Filter by status', 'View profile', 'Download resume', 'Update status', 'Export CSV'],
  users: ['Add user', 'Assign role', 'Search users', 'Filter by role/status', 'User table with pagination'],
  vendors: ['Add vendor', 'Supported languages', 'Assigned projects', 'Capacity tracking', 'Payment status', 'Performance score'],
  'dc-team': ['Add DC team member', 'Assign language', 'Assign project', 'Daily target', 'Attendance tracking', 'Team leader mapping'],
  projects: ['Create new project', 'Language selection', 'Target volume', 'Assign vendors', 'Progress tracking', 'Deadline status'],
  languages: ['Add languages', 'Edit language', 'Active/inactive status', 'Target per language', 'Completed data per language'],
  collection: ['Data intake', 'Language category', 'Vendor assignment', 'Target tracking', 'Collection quality'],
  uploads: ['Submitted files', 'Filter uploads', 'Preview files', 'Download files', 'Bulk approval/rejection'],
  quality: ['Approve data', 'Reject data', 'Rejection reason', 'Duplicate check', 'QC remarks', 'Client approval'],
  payments: ['Vendor summary', 'Approved data calculation', 'Advance payment', 'Final settlement', 'Invoice upload/download'],
  reports: ['Daily report', 'Weekly report', 'Monthly report', 'Vendor-wise report', 'Export CSV, Excel, PDF'],
  settings: ['Logo and favicon', 'Contact settings', 'Social links', 'Company information', 'Notifications', 'Security settings'],
}
